/* Autogenerated by src/archutils/Win32/gen-git-verinfo.bat */

#define BUILD_VERSION	"stupid-placeholder-tag-goddammit-github DEV"
#define BUILD_DATE		"2017-04-14"
#define BUILD_REVISION_TAG	"beta3-379-gc613cc8"
